// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.5
// source: api/wsapi/exchange/exchange.proto

package exchange

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExchangeServiceClient is the client API for ExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeServiceClient interface {
	ExchangeMsg(ctx context.Context, opts ...grpc.CallOption) (ExchangeService_ExchangeMsgClient, error)
}

type exchangeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeServiceClient(cc grpc.ClientConnInterface) ExchangeServiceClient {
	return &exchangeServiceClient{cc}
}

func (c *exchangeServiceClient) ExchangeMsg(ctx context.Context, opts ...grpc.CallOption) (ExchangeService_ExchangeMsgClient, error) {
	stream, err := c.cc.NewStream(ctx, &ExchangeService_ServiceDesc.Streams[0], "/wsapi.exchange.ExchangeService/ExchangeMsg", opts...)
	if err != nil {
		return nil, err
	}
	x := &exchangeServiceExchangeMsgClient{stream}
	return x, nil
}

type ExchangeService_ExchangeMsgClient interface {
	Send(*Msg) error
	Recv() (*Msg, error)
	grpc.ClientStream
}

type exchangeServiceExchangeMsgClient struct {
	grpc.ClientStream
}

func (x *exchangeServiceExchangeMsgClient) Send(m *Msg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exchangeServiceExchangeMsgClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExchangeServiceServer is the server API for ExchangeService service.
// All implementations must embed UnimplementedExchangeServiceServer
// for forward compatibility
type ExchangeServiceServer interface {
	ExchangeMsg(ExchangeService_ExchangeMsgServer) error
	mustEmbedUnimplementedExchangeServiceServer()
}

// UnimplementedExchangeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExchangeServiceServer struct {
}

func (UnimplementedExchangeServiceServer) ExchangeMsg(ExchangeService_ExchangeMsgServer) error {
	return status.Errorf(codes.Unimplemented, "method ExchangeMsg not implemented")
}
func (UnimplementedExchangeServiceServer) mustEmbedUnimplementedExchangeServiceServer() {}

// UnsafeExchangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeServiceServer will
// result in compilation errors.
type UnsafeExchangeServiceServer interface {
	mustEmbedUnimplementedExchangeServiceServer()
}

func RegisterExchangeServiceServer(s grpc.ServiceRegistrar, srv ExchangeServiceServer) {
	s.RegisterService(&ExchangeService_ServiceDesc, srv)
}

func _ExchangeService_ExchangeMsg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExchangeServiceServer).ExchangeMsg(&exchangeServiceExchangeMsgServer{stream})
}

type ExchangeService_ExchangeMsgServer interface {
	Send(*Msg) error
	Recv() (*Msg, error)
	grpc.ServerStream
}

type exchangeServiceExchangeMsgServer struct {
	grpc.ServerStream
}

func (x *exchangeServiceExchangeMsgServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exchangeServiceExchangeMsgServer) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExchangeService_ServiceDesc is the grpc.ServiceDesc for ExchangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wsapi.exchange.ExchangeService",
	HandlerType: (*ExchangeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExchangeMsg",
			Handler:       _ExchangeService_ExchangeMsg_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/wsapi/exchange/exchange.proto",
}
