// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.5
// source: app/ws-api/api/bizmsg/bizmsg.proto

package bizmsg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BizMsgServiceClient is the client API for BizMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BizMsgServiceClient interface {
	Push(ctx context.Context, in *BizMsg, opts ...grpc.CallOption) (*PushBizMsgReply, error)
}

type bizMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBizMsgServiceClient(cc grpc.ClientConnInterface) BizMsgServiceClient {
	return &bizMsgServiceClient{cc}
}

func (c *bizMsgServiceClient) Push(ctx context.Context, in *BizMsg, opts ...grpc.CallOption) (*PushBizMsgReply, error) {
	out := new(PushBizMsgReply)
	err := c.cc.Invoke(ctx, "/wsapi.bizmsg.BizMsgService/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BizMsgServiceServer is the server API for BizMsgService service.
// All implementations must embed UnimplementedBizMsgServiceServer
// for forward compatibility
type BizMsgServiceServer interface {
	Push(context.Context, *BizMsg) (*PushBizMsgReply, error)
	mustEmbedUnimplementedBizMsgServiceServer()
}

// UnimplementedBizMsgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBizMsgServiceServer struct {
}

func (UnimplementedBizMsgServiceServer) Push(context.Context, *BizMsg) (*PushBizMsgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedBizMsgServiceServer) mustEmbedUnimplementedBizMsgServiceServer() {}

// UnsafeBizMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BizMsgServiceServer will
// result in compilation errors.
type UnsafeBizMsgServiceServer interface {
	mustEmbedUnimplementedBizMsgServiceServer()
}

func RegisterBizMsgServiceServer(s grpc.ServiceRegistrar, srv BizMsgServiceServer) {
	s.RegisterService(&BizMsgService_ServiceDesc, srv)
}

func _BizMsgService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BizMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BizMsgServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wsapi.bizmsg.BizMsgService/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BizMsgServiceServer).Push(ctx, req.(*BizMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// BizMsgService_ServiceDesc is the grpc.ServiceDesc for BizMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BizMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wsapi.bizmsg.BizMsgService",
	HandlerType: (*BizMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _BizMsgService_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/ws-api/api/bizmsg/bizmsg.proto",
}
