// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/lyouthzzz/ws-gateway/app/ws-api/internal/config"
	"github.com/lyouthzzz/ws-gateway/app/ws-api/internal/server"
	"github.com/lyouthzzz/ws-gateway/app/ws-api/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func initApp(configServer *config.Server, registry *config.Registry, logger log.Logger) (*kratos.App, error) {
	exchangeService := service.NewExchangeService()
	v := server.NewServers(configServer, exchangeService)
	registrar := server.NewRegistry(registry)
	app := newApp(logger, v, registrar)
	return app, nil
}
