// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/lyouthzzz/ws-gateway/app/ws-gateway/internal/config"
	"github.com/lyouthzzz/ws-gateway/app/ws-gateway/internal/gateway"
	"github.com/lyouthzzz/ws-gateway/app/ws-gateway/internal/server"
)

import (
	_ "go.uber.org/automaxprocs"
	_ "net/http/pprof"
)

// Injectors from wire.go:

func initApp(configServer *config.Server, registry *config.Registry, websocketGateway *gateway.WebsocketGateway, logger log.Logger) (*kratos.App, error) {
	v := server.NewServers(configServer, websocketGateway, logger)
	registrar := server.NewRegistry(registry)
	app := newApp(logger, v, registrar)
	return app, nil
}
