// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.5
// source: app/ws-api/api/exchange/exchange.proto

package exchange

import (
	protocol "github.com/lyouthzzz/ws-gateway/app/ws-gateway/api/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid       uint64             `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	GatewayIP string             `protobuf:"bytes,2,opt,name=gatewayIP,proto3" json:"gatewayIP,omitempty"`
	Payload   *protocol.Protocol `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_ws_api_api_exchange_exchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_app_ws_api_api_exchange_exchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_app_ws_api_api_exchange_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *Msg) GetGatewayIP() string {
	if x != nil {
		return x.GatewayIP
	}
	return ""
}

func (x *Msg) GetPayload() *protocol.Protocol {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_app_ws_api_api_exchange_exchange_proto protoreflect.FileDescriptor

var file_app_ws_api_api_exchange_exchange_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x70, 0x2f, 0x77, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x77, 0x73, 0x61, 0x70, 0x69, 0x2e,
	0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6b, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x50, 0x12, 0x34, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x50,
	0x0a, 0x0f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x13, 0x2e, 0x77, 0x73, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x2e, 0x4d, 0x73, 0x67, 0x1a, 0x13, 0x2e, 0x77, 0x73, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x79, 0x6f, 0x75, 0x74, 0x68, 0x7a, 0x7a, 0x7a, 0x2f, 0x77, 0x73, 0x2d, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x77, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_app_ws_api_api_exchange_exchange_proto_rawDescOnce sync.Once
	file_app_ws_api_api_exchange_exchange_proto_rawDescData = file_app_ws_api_api_exchange_exchange_proto_rawDesc
)

func file_app_ws_api_api_exchange_exchange_proto_rawDescGZIP() []byte {
	file_app_ws_api_api_exchange_exchange_proto_rawDescOnce.Do(func() {
		file_app_ws_api_api_exchange_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_ws_api_api_exchange_exchange_proto_rawDescData)
	})
	return file_app_ws_api_api_exchange_exchange_proto_rawDescData
}

var file_app_ws_api_api_exchange_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_ws_api_api_exchange_exchange_proto_goTypes = []interface{}{
	(*Msg)(nil),               // 0: wsapi.exchange.Msg
	(*protocol.Protocol)(nil), // 1: gateway.protocol.Protocol
}
var file_app_ws_api_api_exchange_exchange_proto_depIdxs = []int32{
	1, // 0: wsapi.exchange.Msg.payload:type_name -> gateway.protocol.Protocol
	0, // 1: wsapi.exchange.ExchangeService.ExchangeMsg:input_type -> wsapi.exchange.Msg
	0, // 2: wsapi.exchange.ExchangeService.ExchangeMsg:output_type -> wsapi.exchange.Msg
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_ws_api_api_exchange_exchange_proto_init() }
func file_app_ws_api_api_exchange_exchange_proto_init() {
	if File_app_ws_api_api_exchange_exchange_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_ws_api_api_exchange_exchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_ws_api_api_exchange_exchange_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_ws_api_api_exchange_exchange_proto_goTypes,
		DependencyIndexes: file_app_ws_api_api_exchange_exchange_proto_depIdxs,
		MessageInfos:      file_app_ws_api_api_exchange_exchange_proto_msgTypes,
	}.Build()
	File_app_ws_api_api_exchange_exchange_proto = out.File
	file_app_ws_api_api_exchange_exchange_proto_rawDesc = nil
	file_app_ws_api_api_exchange_exchange_proto_goTypes = nil
	file_app_ws_api_api_exchange_exchange_proto_depIdxs = nil
}
