version: "3.3"

services:
  ws-gateway:
    container_name: ws-gateway
    image: ws-gateway
    environment:
      APP_NAME: ws-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ws-api
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
        reservations:
          cpus: 1
          memory: 2G
    command:
      - /app/ws-gateway --ws_api_endpoint ws-api:8081
  ws-api:
    container_name: ws-api
    image: ws-api
    environment:
      APP_NAME: ws-api
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
        reservations:
          cpus: 1
          memory: 2G